[package]
name = "ice40pnr"
version = "0.1.0"
edition = "2024"

[profile.dev.package.zstd]
opt-level = 3

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
zstd = "0.13.2"
